name: iabtcf_consent_info
description: >- 
  Flutter plugin for reading IAB TCF v2.0 user consent information, such as 
  made available through CMP SDKs, like Funding Choices's 
  User Messaging Platform (UMP).
version: 3.0.0
repository: https://github.com/blaugold/iabtcf_consent_info
issue_tracker: https://github.com/blaugold/iabtcf_consent_info/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  rxdart: '>=0.26.0 <0.28.0'
  iabtcf_consent_info_platform_interface: ^1.0.5
  iabtcf_consent_info_web: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: IabtcfConsentInfoPlugin
      android:
        package: com.terwesten.gabriel.iabtcf_consent_info
        pluginClass: IabtcfConsentInfoPlugin
      web:
        default_package: iabtcf_consent_info_web
